
services:
  ticketsapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: tickets_web_api
    depends_on:
      - db
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: tickets-database
    volumes:
      - db_data:/var/lib/postgresql/data
    container_name: postgres_container
  migrator:
    image: mcr.microsoft.com/dotnet/sdk:9.0
    working_dir: /app/WebApi
    volumes:
      - .:/app
    depends_on:
      - db
    entrypoint: [ "dotnet", "ef", "database", "update" ]
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=tickets-database;Username=postgres;Password=1234
  redis_service:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

volumes:
  db_data: