
services:
  ticketsapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: tickets_web_api
    depends_on:
      - db
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: tickets-database
    volumes:
      - db_data:/var/lib/postgresql/data
    container_name: postgres_container
volumes:
  db_data: